const languageData = {
    name: "李嘉豪",
    name_sub: "一名业余的前端工程师",
    about_1: "男 | 已婚 | 1988.07",
    about_2: "居住于深圳，惠州",
    about_3: "广东人 | 粤语 | 客家话",
    skills: "技能",
    Frontend: "前端",
    Backend: "后台",
    Tool: "工具",
    Others: "其他",
    work_step1: "2011.07",
    work_tit1: "从广东工业大学毕业",
    work_step2: "2011.07 - 2016.04",
    work_tit2: "TCL通讯科技控股有限公司",
    work_detail2: "刚入职是当网络工程师，1年后因工作热情抽调到新组建的研发团队，开启我的编码之旅。 主要负责公司oa系统开发。",
    work_step3: "2016.06 - 至今",
    work_tit3: "OMG昂沃斯科技(深圳)有限公司",
    work_detail3: "职位是前端工程师，主要负责公司页面开发以及部分后台开发。",
    Home: "首页",
    About: "关于",
    Experience: "经历",
    Portfolio: "作品"
};
export default languageData;
